# create the conda environment : $ conda env create
# activate the conda environment
# update conda env using: conda env update -f <filename>.yml or simply conda env update
# then create .env file (copy from other .env files, ...)

name: cs285_2023
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - pip
  - pip:
    - mujoco==2.2.0
    - gym==0.25.2
    - tensorboard==2.10.0
    - tensorboardX==2.5.1
    - matplotlib==3.5.3
    - ipython==7.34.0
    - moviepy==1.0.3
    - pyvirtualdisplay==3.0
    - torch==1.12.1
    - opencv-python==4.6.0.66
    - ipdb==0.13.9
    - swig==4.0.2
    - box2d-py==2.3.8

